version: '3.8'

services:
  mongo:
    image: docker.io/zcube/bitnami-compat-mongodb:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - fastfood-network
    environment:
      MONGODB_USERNAME: common_user
      MONGODB_PASSWORD: password123
      MONGODB_DATABASE: fastfood
      MONGODB_ROOT_PASSWORD: rootpassword
    volumes:
      - 'mongodb_data:/fastfood'

  fastfood:
    container_name: fiap-fastfood
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - fastfood-network
    environment:
      SPRING_PROFILES_ACTIVE: local
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: rootpassword
      MONGODB_DATABASE: fastfood
      MONGODB_AUTHDB: admin

volumes:
  mongodb_data:
    driver: local

networks:
  fastfood-network:
    driver: bridge