apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/fiap-fastfood-network: "true"
        io.kompose.service: mongo
    spec:
      containers:
        - env:
            - name: MONGODB_DATABASE
              value: fastfood
            - name: MONGODB_PASSWORD
              value: password123
            - name: MONGODB_ROOT_PASSWORD
              value: rootpassword
            - name: MONGODB_USERNAME
              value: common_user
          image: docker.io/zcube/bitnami-compat-mongodb:5.0
          name: mongo
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /fiap-fastfood
              name: mongodb-data
      restartPolicy: Always
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
